### ISSUE TITLE
Handle end of database gracefuly

### ISSUE THREAD

**Issue by tomusdrw** [debris/paritydb#20]
Currently we will panic if we reach the end of DB (while trying to flush data)

**Comment by snd** [comment]
@debris @tomusdrw 

adding to this issue instead of opening a seperate one.

after getting an understanding of paritydb and where in parity it would be used i started writing further benchmarks. in a seperate dir for now since i got an error that two crates link against the same native lib (rocksdb) after adding `ethcore-util = { git = "https://github.com/paritytech/parity" }` to `benchmarks/Cargo.toml`.

doing `cd benchmarks_realworld` and then `cargo bench` errors with:

```
cargo bench
    Finished release [optimized] target(s) in 0.0 secs
     Running /Users/basilisk/workspace/paritydb/target/release/deps/benchmarks_realworld-2bfbaa7990d01507

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running /Users/basilisk/workspace/paritydb/target/release/deps/account-f23a94bdf2584e81

running 1 test
test paritydb_10000_account_get ... before commit
before flush
thread 'main' panicked at 'TODO: db end?', src/libcore/option.rs:874:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: bench failed
```

relevant section: `thread 'main' panicked at 'TODO: db end?', src/libcore/option.rs:874:4`

the failing code fails here:
https://github.com/paritytech/paritydb/blob/realworld_benchmarks/benchmarks_realworld/benches/account.rs#L33

managed to trace the cause to here:
https://github.com/paritytech/paritydb/blob/master/paritydb/src/flush/writer.rs#L156

i'd be interested in fixing this and appreciate any pointers!

this is not blocking me from writing benchmarks. simply wanted to document it.

**Comment by tomusdrw** [comment]
As mentioned in #45: Ideally end of the database is never reached, the Database should use `Options::extend_threshold_percent` and should re-organize itself (increase `key_index_bits` and copy data over). That's not implemented yet, so the error actually means: "Your database is full."
